create table if not exists visited_countries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  country_code text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, country_code)
);

alter table visited_countries enable row level security;

create policy "Users can view their own data" 
  on visited_countries for select 
  using (auth.uid() = user_id);

create policy "Users can insert their own data" 
  on visited_countries for insert 
  with check (auth.uid() = user_id);

create policy "Users can delete their own data" 
  on visited_countries for delete 
  using (auth.uid() = user_id);
